### ISSUE TITLE
Can't download the reference 

### ISSUE THREAD

**Issue by TinaYibingChen** [UW-GAC/admix-kit_workflow#4]
Hi, I just tried to copy the [simulation example code](https://kangchenghou.github.io/admix-kit/cli/simulate.html#simulation) and run it.  After the setup step (in the prepare source data section), I can't run 
admix get-1kg-ref --dir ${REF_DATA_DIR} --build ${BUILD}. 

It gave me an error:
CalledProcessError: Command 'b'# genome build to use\nBUILD=hg19\n# number of admixed individuals to simulate\nN_INDIV=100000\n# chromosome \nCHROM=22\n# number of generations\nN_GEN=8\n\n# setup\nREF_DATA_DIR=data/1kg-ref-${BUILD}\nRAW_DATA_DIR=data/raw\nGENO_DATA_DIR=data/geno\nmkdir -p ${RAW_DATA_DIR}\nmkdir -p ${GENO_DATA_DIR}\n\n# Create the necessary directories if they do not already exist\nmkdir -p ${RAW_DATA_DIR}\nmkdir -p ${GENO_DATA_DIR}\n\nadmix get-1kg-ref --dir ${REF_DATA_DIR} --build ${BUILD}\n\n'' returned non-zero exit status 1.

I wonder if I need to download anything or provide more information rather than copy and paste. Thank you very much!

**Comment by smgogarten** [comment]
This issue does not seem related to the WDL workflow, so please report it on the main admix-kit page: https://github.com/KangchengHou/admix-kit/issues
